[package]
name = "payjoin-blackpill-test"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
payjoin = { git = "https://github.com/caarloshenriq/rust-payjoin", branch = "feat/payjoin-nostd", default-features = false, features = [
  "alloc",
  "v1",
  "v2",
] }
cortex-m = { version = "0.7.6", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7"
panic-halt = "1.0"
linked_list_allocator = "0.10"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
incremental = false
debug = 2
split-debuginfo = "unpacked"
